#!/bin/bash

CONFIG="SimpleHome.simpleconfig"
echo Welcome, $user!
echo This is the SimpleScript Home Page Maker! This script will create a home page or override your existing home page with a blank one!
echo Make sure that you are in the Home Directory for your project/
echo Press enter to continue, or press control+c to abort
read consent
echo Awesome! I will make a new home page.
mkdir $name
cd $name
touch index.html
touch index.simple
cat "./index.html" >> "$CONFIG"
echo "Created index.html (You don't have to worry about this)"
echo Added Simple Script!
echo You are ready to go!
cd ..
